### ISSUE TITLE
[question] question about Xpra

### ISSUE THREAD

**Issue by ninrod** [JAremko/docker-emacs#1]
Hi @JAremko. 

Why do you choose to use Xpra instead of, for example, the cygwin xserver? I'm using emacs inside docker on windows at work and found this very interesting. What does it do better, exactly? thanks in advance.

**Comment by JAremko** [comment]
Hi @ninrod 
 I decided to go with Xpra because:
- It has a client for all major platforms (even Android and web-browser)
- It is persistent. You can connect from one device, disconnect and reconnect from the other one without disrupting Emacs.
- Since it does most of the work at the docker side, it is likely to behave in the same way across different platforms. So we'll have to(hopefully) solve less platform specific bugs.

More pros and cons   [here](https://github.com/JAremko/spacemacs-pr/blob/spacemacs-docker/layers/%2Bdistributions/spacemacs-docker/README.org#features)

**Comment by ninrod** [comment]
thanks jaremko.
