### ISSUE TITLE
Windows launch

### ISSUE THREAD

**Issue by neeasade** [JAremko/docker-emacs#6]
Hi there, 

I'm trying to get this to launch on windows and it's not currently. I've installed cygwin with xhost, xinit/startxwin, and I created a script which I launch from cygwin shell:

``` sh
#!/bin/bash

set -e

ip="$(ipconfig | grep IPv4 | tail -n 1 | sed 's/.*: //' | tr -d $'\n\r')"
export DISPLAY="${ip}:0.0"

(
startxwin -- -listen tcp &
xhost ${ip}
) &

sleep 3

docker run --name emacs \
       -e DISPLAY="unix$DISPLAY" \
       -e UNAME="emacser" \
       -e GNAME="emacsers" \
       -e UID="1000" \
       -e GID="1000" \
       -v "$HOME/.emacs.d:/home/emacs/.emacs.d" \
       -v "$HOME/.spacemacs.d:/home/emacs/.spacemacs.d" \
       -v "$HOME/git:/mnt/workspace" \
       jare/emacs emacs
```

and I get:

```
Display unix10.1.16.121:0.0 unavailable, simulating -nw
emacs: standard input is not a tty
```

I can see XWin in the tray, on `:0.0`, and have verified ip in script above

**Comment by JAremko** [comment]
@neeasade  What kind of Docker(Docker for Windows or Docker Toolbox) and Windows you have?

**Comment by neeasade** [comment]
docker for windows, docker --version is `Docker version 17.06.1-ce, build 874a737`

**Comment by JAremko** [comment]
@neeasade  does it work with `xhost +` instead of `xhost ${ip}` ?  also  try ` -e DISPLAY="$DISPLAY" \` instead of ` -e DISPLAY="unix$DISPLAY" \` just to be sure :smile: 

- - - - - -

Or mb script gets wrong IP. You can try setting `ip` var  to your local or public IP. 

- - - - - -

btw the  README says  `xhost + <your-machine-ip>` not `xhost <your-machine-ip>` - this is how I tested it.
